server:
  port: 8080
  servlet:
    context-path: /duocoding
spring:
  application:
    name: duocoding
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:duocoding}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:migration
    table: flyway_schema_history
